### ISSUE TITLE
Make plugin UUID ready

### ISSUE THREAD

**Issue by TakeMeNL** [deathmarine/Ultrabans#39]
As title says

**Comment by TekkitCommando** [comment]
I have been working to become the new owner of Ultrabans I should have a UUID update really soon, this plugin will never be dead it's to awesome :)

**Comment by CLGREEN94** [comment]
> TekkitCommando this makes me happy! Should we follow your work on your GitHub? 

Thank-you, this message was sent to you from Callum Green's iPhone.

**Comment by TekkitCommando** [comment]
You can do either one it doesnt matter to me :)
